apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: dishantsethi/dockerizeproject_web:latest
    imagePullPolicy: IfNotPresent
  - name: db-container
    image: postgres
    env:
    - name: POSTGRES_DB
      value: postgres
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    imagePullPolicy: IfNotPresent
